export const SCALE_FACTOR = 0.67;

export const RADIUS_BASE = 265;
export const RADIUS = RADIUS_BASE * SCALE_FACTOR;

export const CIRCLE_SIZE_BASE = 530;
export const CIRCLE_SIZE = CIRCLE_SIZE_BASE * SCALE_FACTOR;

export const DOT_SIZE_SMALL_BASE = 6;
export const DOT_SIZE_LARGE_BASE = 56;
export const DOT_SIZE_SMALL = DOT_SIZE_SMALL_BASE * SCALE_FACTOR;
export const DOT_SIZE_LARGE = DOT_SIZE_LARGE_BASE * SCALE_FACTOR;

export const SCALE_CLOSED = DOT_SIZE_SMALL / DOT_SIZE_LARGE;

export const CONTENT_OFFSET_X_BASE = 76;
export const CONTENT_OFFSET_X = CONTENT_OFFSET_X_BASE * SCALE_FACTOR;

export const DOT_CONTENT_SIZE_BASE = 54;
export const DOT_CONTENT_SIZE = DOT_CONTENT_SIZE_BASE * SCALE_FACTOR;
